leftnav:
- identifier: b5eb0231-7b74-fd9c-b33d-116d69a4679f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: b95fce95-24f3-f444-b5b4-84026108a286
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 40ed4c8c-6a49-d11b-c16b-2a3d3a34ea4c
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
- identifier: 3e09c437-98cf-4610-62c5-043bad349075
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 40
